name: sogreen_wp72_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310hf3fd67a_0
  - branca=0.6.0=py310hecd8cb5_0
  - brotlicffi=1.0.9.2=py310h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - certifi=2025.8.3=py310hecd8cb5_0
  - cffi=1.17.1=py310h9205ec4_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h26e2fd1_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - folium=0.14.0=py310hecd8cb5_0
  - geos=3.10.6=h6d0c2b6_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=ha357a0b_43548
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310hecd8cb5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h37d8d59_0
  - libcxx=19.1.7=haebbb44_3
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libffi=3.4.4=hecd8cb5_1
  - libsodium=1.0.20=hfdf4475_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h8e150cf_43560
  - mkl-service=2.4.0=py310h46256e1_2
  - mkl_fft=1.3.8=py310h6c40b1e_0
  - mkl_random=1.2.4=py310ha357a0b_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.8.7=py310h827a554_0
  - numpy-base=1.26.4=py310ha186be2_0
  - openssl=3.5.3=h230baf5_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py310hd2d5e8d_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py310hecd8cb5_0
  - python=3.10.18=hc958d9f_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=py310hecd8cb5_0
  - pyzmq=27.1.0=py310hbbd5e6a_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py310hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=ha357a0b_0
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.2=py310h1b7cace_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310hecd8cb5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4b97444_1
  - pip:
      - aiofiles==25.1.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - binaryornot==0.4.4
      - bleach==6.2.0
      - build==1.3.0
      - cachetools==6.2.0
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - click==8.1.8
      - click-default-group==1.2.4
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - contourpy==1.3.2
      - cookiecutter==2.6.0
      - coverage==7.10.7
      - cycler==0.12.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - dynaconf==3.2.11
      - et-xmlfile==2.0.0
      - fastapi==0.120.4
      - fastjsonschema==2.21.2
      - fiona==1.10.1
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - geoalchemy2==0.18.0
      - geojson==3.2.0
      - geopandas==1.1.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - idna==3.10
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jiter==0.11.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kedro==1.0.0
      - kedro-datasets==8.1.0
      - kedro-telemetry==0.6.5
      - kedro-viz==12.1.0
      - kiwisolver==1.4.9
      - lark==1.3.0
      - lazy-loader==0.4
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mistune==3.1.4
      - more-itertools==10.8.0
      - narwhals==2.7.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - ollama==0.6.0
      - omegaconf==2.3.0
      - openai==2.3.0
      - openpyxl==3.1.5
      - orjson==3.11.4
      - osmnx==2.0.6
      - overrides==7.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parse==1.20.2
      - pathspec==0.12.1
      - pillow==11.3.0
      - plotly==6.3.1
      - pluggy==1.6.0
      - prometheus-client==0.23.1
      - psycopg2-binary==2.9.11
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pyogrio==0.11.1
      - pyparsing==3.2.5
      - pyproj==3.7.1
      - pyproject-hooks==1.2.0
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-slugify==8.0.4
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - seaborn==0.13.2
      - secure==1.0.1
      - send2trash==1.8.3
      - shapely==2.1.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - starlette==0.49.3
      - terminado==0.18.1
      - text-unidecode==1.3
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.2.1
      - tomli-w==1.2.0
      - tqdm==4.67.1
      - types-python-dateutil==2.9.0.20250822
      - typing-inspection==0.4.2
      - uri-template==1.3.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
